DROP TABLE IF EXISTS `TestDB`.`TBL_USER`; CREATE TABLE `TestDB`.`TBL_USER` ( `ID` INT(8) NOT NULL AUTO_INCREMENT ,  `chat_id` BIGINT NOT NULL ,  `record_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,    PRIMARY KEY  (`ID`)) ENGINE = InnoDB;
COMMIT;
